"""
backend/report.py
PDF report generation for RETINAsync screening results.
Uses ReportLab.
"""

import os
import io
from datetime import datetime
from PIL import Image as PILImage

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")


def _pil_to_bytes(pil_img: PILImage.Image, fmt: str = "PNG") -> bytes:
    buf = io.BytesIO()
    pil_img.save(buf, format=fmt)
    return buf.getvalue()


def generate_report(patient: dict, screening: dict, gradcam_result,
                    original_img) -> "str | None":
    """
    Generate a PDF screening report and save to reports/.

    Args:
        patient:       dict with patient fields
        screening:     dict with screening result fields
        gradcam_result: dict from generate_gradcam() or None
        original_img:  PIL Image of the original retinal photo or None

    Returns:
        Absolute path to the saved PDF, or None on failure.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import mm, cm
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, Image as RLImage, KeepTogether
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

        os.makedirs(REPORTS_DIR, exist_ok=True)
        screening_id = screening.get("screening_id", "UNKNOWN")
        filename = f"RETINAsync_Report_{screening_id}.pdf"
        filepath = os.path.join(REPORTS_DIR, filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "Title", parent=styles["Title"],
            fontSize=22, textColor=colors.HexColor("#0f3460"),
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            "Subtitle", parent=styles["Normal"],
            fontSize=11, textColor=colors.HexColor("#1a73a7"),
            spaceAfter=12, alignment=TA_CENTER
        )
        section_style = ParagraphStyle(
            "Section", parent=styles["Heading2"],
            fontSize=13, textColor=colors.HexColor("#0f3460"),
            spaceBefore=12, spaceAfter=6,
            borderPad=4,
        )
        body_style = ParagraphStyle(
            "Body", parent=styles["Normal"],
            fontSize=10, leading=14
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer", parent=styles["Normal"],
            fontSize=8, textColor=colors.HexColor("#dc2626"),
            leading=11, spaceBefore=8
        )
        label_style = ParagraphStyle(
            "Label", parent=styles["Normal"],
            fontSize=9, textColor=colors.grey, leading=12
        )

        story = []

        # ── Header ────────────────────────────────────────────────────────────
        story.append(Paragraph("RETINAsync", title_style))
        story.append(Paragraph("Explainable AI for Diabetic Retinopathy Screening", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#0f3460")))
        story.append(Spacer(1, 6 * mm))

        # ── Screening metadata ─────────────────────────────────────────────────
        story.append(Paragraph("Screening Report", section_style))
        meta_data = [
            ["Screening ID",    screening_id],
            ["Date & Time",     screening.get("screening_date", datetime.now().strftime("%Y-%m-%d %H:%M"))],
            ["Generated By",    "RETINAsync v1.0 (Prototype)"],
        ]
        meta_table = Table(meta_data, colWidths=[60 * mm, 110 * mm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4fd")),
            ("TEXTCOLOR",  (0, 0), (0, -1), colors.HexColor("#0f3460")),
            ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fbfe")]),
            ("PADDING",    (0, 0), (-1, -1), 5),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 6 * mm))

        # ── Patient information ────────────────────────────────────────────────
        story.append(Paragraph("Patient Information", section_style))
        patient_data = [
            ["Patient ID",   patient.get("patient_id", "N/A")],
            ["Name",         patient.get("name", "N/A")],
            ["Age",          str(patient.get("age", "N/A"))],
            ["Gender",       patient.get("gender", "N/A")],
            ["Phone",        patient.get("phone", "—") or "—"],
            ["Village",      patient.get("village", "—") or "—"],
        ]
        pt_table = Table(patient_data, colWidths=[60 * mm, 110 * mm])
        pt_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4fd")),
            ("TEXTCOLOR",  (0, 0), (0, -1), colors.HexColor("#0f3460")),
            ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fbfe")]),
            ("PADDING",    (0, 0), (-1, -1), 5),
        ]))
        story.append(pt_table)
        story.append(Spacer(1, 6 * mm))

        # ── Quality Gate results ───────────────────────────────────────────────
        story.append(Paragraph("Image Quality Assessment", section_style))
        q_status = screening.get("quality_status", "N/A")
        q_color  = colors.HexColor("#16a34a") if q_status == "PASS" else colors.HexColor("#dc2626")
        quality_data = [
            ["Metric",          "Score",                                     "Status"],
            ["Blur Score",      str(screening.get("blur_score", "—")),       "—"],
            ["Illumination",    str(screening.get("illumination_score","—")), "—"],
            ["Field of View",   f"{screening.get('fov_score','—')}%",        "—"],
            ["Overall Quality", "",                                           q_status],
        ]
        q_table = Table(quality_data, colWidths=[60 * mm, 55 * mm, 55 * mm])
        q_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0),  colors.HexColor("#0f3460")),
            ("TEXTCOLOR",   (0, 0), (-1, 0),  colors.white),
            ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fbfe")]),
            ("PADDING",     (0, 0), (-1, -1), 5),
            ("TEXTCOLOR",   (2, -1), (2, -1), q_color),
            ("FONTNAME",    (2, -1), (2, -1), "Helvetica-Bold"),
        ]))
        story.append(q_table)
        story.append(Spacer(1, 6 * mm))

        # ── AI Result ─────────────────────────────────────────────────────────
        story.append(Paragraph("AI Screening Result", section_style))
        grade = screening.get("predicted_grade", "N/A")
        grade_str = f"Grade {grade}" if grade != "N/A" else "N/A"
        risk   = screening.get("risk_level", "N/A")
        ref    = screening.get("referral_status", "N/A")
        conf   = screening.get("confidence", "N/A")
        pred_class = screening.get("predicted_class", "N/A")
        is_demo = screening.get("is_demo", 1)

        result_data = [
            ["DR Grade",           grade_str],
            ["Classification",     pred_class],
            ["Confidence",         f"{conf}%" if conf != "N/A" else "N/A"],
            ["Risk Level",         risk],
            ["Referral Support",   ref],
            ["Result Type",        "⚠ DEMONSTRATION" if is_demo else "Model Prediction"],
        ]
        res_table = Table(result_data, colWidths=[60 * mm, 110 * mm])
        res_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4fd")),
            ("TEXTCOLOR",  (0, 0), (0, -1), colors.HexColor("#0f3460")),
            ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fbfe")]),
            ("PADDING",    (0, 0), (-1, -1), 5),
        ]))
        story.append(res_table)
        story.append(Spacer(1, 6 * mm))

        # ── Images ────────────────────────────────────────────────────────────
        img_items = []
        img_width = 70 * mm

        if original_img is not None:
            try:
                buf = io.BytesIO()
                original_img.convert("RGB").save(buf, format="PNG")
                buf.seek(0)
                rl_img = RLImage(buf, width=img_width, height=img_width)
                img_items.append([rl_img, Paragraph("Original Retinal Image", label_style)])
            except Exception:
                pass

        if gradcam_result and gradcam_result.get("overlay_pil"):
            try:
                buf = io.BytesIO()
                gradcam_result["overlay_pil"].convert("RGB").save(buf, format="PNG")
                buf.seek(0)
                rl_img = RLImage(buf, width=img_width, height=img_width)
                label_txt = "Grad-CAM Overlay (DEMO)" if gradcam_result.get("is_demo") else "Grad-CAM Overlay"
                img_items.append([rl_img, Paragraph(label_txt, label_style)])
            except Exception:
                pass

        if img_items:
            story.append(Paragraph("Retinal Images", section_style))
            for item in img_items:
                story.append(KeepTogether([item[0], Spacer(1, 2 * mm), item[1], Spacer(1, 4 * mm)]))
            story.append(Spacer(1, 4 * mm))

        # ── Disclaimer ────────────────────────────────────────────────────────
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dc2626")))
        disclaimer_text = (
            "<b>IMPORTANT DISCLAIMER:</b> This report is generated by RETINAsync, "
            "a research and hackathon prototype developed for the Smart India Hackathon (SIH 2026). "
            "It is NOT a certified medical device and does NOT constitute a clinical diagnosis. "
            "All results are for demonstration and research purposes only. "
            "This prototype must NOT be used for actual patient diagnosis or treatment decisions. "
            "Any screening findings must be reviewed and confirmed by a qualified ophthalmologist "
            "or medical professional. The AI predictions shown are prototype outputs and have not "
            "been clinically validated."
        )
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph(disclaimer_text, disclaimer_style))

        doc.build(story)
        return filepath

    except ImportError:
        print("[report.py] ReportLab not installed. PDF generation skipped.")
        return None
    except Exception as e:
        print(f"[report.py] Report generation error: {e}")
        return None
